beapro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('student/',include('student.urls')),
    path('tutor/',include('tutor.urls')),
    path('blog/', include('blogapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "BEAPRO Admin"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to BEAPRO Admin Account"

blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.MainView, name='MainView'),
    path('post/<int:pk>', views.PostDetailView, name='PostDetailView'),
    path('post/create', views.PostCreateView.as_view(), name='PostCreateView'),
    path('post/<int:pk>/edit', views.PostEditView.as_view(), name='PostEditView'),
    path('post/<int:pk>/approve', views.ApprovePost, name='ApprovePost'),
    path('myposts/', views.MyArticlesView, name='MyArticlesView'),
    path('likepost/<int:pk>', views.LikePost, name='LikePost'),
    path('noaccess/', views.NoAccess, name='NoAccess'),
    # path('login/', views.LoginView, name='LoginView'),
    path('logout/', views.LogoutView, name='LogoutView'),
] 

tutor/urls.py
from django.urls import path
from .views import account_signup,account_login,logout_tutor,tutor_profile,connection_requests,decline_connection_request,connection_list_view,remove_connection_student


urlpatterns = [
    path('account/',account_login,name="tutor_account_login"),
    path('account/signup',account_signup,name="tutor_account_signup"),
    path('logout',logout_tutor, name="logout_tutor"),

    path('list/<user_id>', connection_list_view, name='student-list'),
    path('profile/',tutor_profile, name="tutor_profile"),
    path('connection_requests/<user_id>/',connection_requests,name='connection-requests'),
    path('remove_connection_student/',remove_connection_student,name='remove-connection-student'),
    path('decline_connection_request/<connection_request_id>/', decline_connection_request, name='decline-connection-request'),

]

blogapp/models.py
from django.db import models
from django.db.models.fields import CharField
from accounts.models import Account
from django.shortcuts import reverse



class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "categories"

class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Account, on_delete=models.CASCADE)
    body = models.TextField(blank=True)
    snippet = models.TextField()
    post_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('Category', null=True, on_delete=models.SET_NULL)
    visible = models.BooleanField(default=False)
    likes = models.IntegerField(default=0)
    locked = models.BooleanField(default=False)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:PostDetailView', args=[self.pk])


class PostLiked(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.ForeignKey(Account, on_delete=models.CASCADE)
    post_id = models.CharField(max_length=(5),blank=True)

    
    

class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    body = models.TextField()
    author = models.CharField(max_length=128)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    visible = models.BooleanField(default=False)
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return 'Comment from' + '|' + self.author
    class Meta:
        ordering = ['-pk']

blogapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from django.views.generic import CreateView, UpdateView
from django.contrib import messages,auth
from .models import Post, Comment, Category,PostLiked
from django.contrib.auth import authenticate, login, logout

def MainView(request):
    posts = Post.objects.filter(visible=True)
    categories = Category.objects.all()
    category = ''
    if request.method == 'GET':
        if 'category' in request.GET:
            category = request.GET['category']
            if category != 'All':
                posts = Post.objects.filter(category__name=category, visible=True)
    ctx = {'posts' : posts.order_by('-post_date'), 'category' : category, 'categories' : categories}
    return render(request, 'blogapp/mainview.html', ctx)

def PostDetailView(request, pk):
    post = Post.objects.get(pk=pk)
    if post.visible == True or request.user.is_superuser or post.author == request.user:
        if request.method == 'POST':
            name = request.POST.get('name')
            comment = request.POST.get('comment')
            comment = Comment(body=comment, author=name, post=post, visible=False)
            comment.save()
            messages.info(request, 'Thank you for your comment. It is sent for review and will appear under the post very soon.')
        comments = Comment.objects.filter(post=post, visible=True)
        ctx = {'post': post, 'comments' : comments}
        return render(request, 'blogapp/postview.html', ctx)
    else:
        return redirect('compapp:NoAccess')

def LikePost(request, pk):
    user = request.user
    post = Post.objects.get(pk=pk)
    postlike = PostLiked.objects.filter(name=user,post_id=pk).exists()
    if postlike:
        return redirect('blog:PostDetailView', pk)
    else:
        likeduser = PostLiked.objects.create(name=user,post_id=pk)
        likeduser.save()
        post.likes = post.likes + 1
        post.save()
        messages.info(request, 'I\'m glad you liked the article. Thank you for reading!')
        return redirect('blog:PostDetailView', pk)

@method_decorator(login_required(), 'dispatch')
class PostCreateView(CreateView):
    model = Post
    fields = ['title', 'body', 'snippet', 'category']
    success_url = reverse_lazy('blog:MainView')
    def form_valid(self, form):
        object = form.save(commit=False)
        object.author = self.request.user
        object.save()
        post = Post.objects.get(pk=object.pk)
        messages.info(self.request, 'Your post is saved and sent for review. Once it is approved, it will be published.')
        return super(PostCreateView, self).form_valid(form)

@method_decorator(login_required(), 'dispatch')
class PostEditView(UpdateView):
    model = Post
    fields = ['title', 'body', 'snippet', 'category']
    success_url = reverse_lazy('blog:MainView')
    def get_queryset(self):
        qs = super(PostEditView, self).get_queryset()
        if self.request.user.is_superuser:
            return qs
        else:
            return qs.filter(author=self.request.user, locked=False)

@login_required()
def MyArticlesView(request):
    posts = Post.objects.filter(author=request.user)
    categories = []
    for post in posts:
        if not post.category in categories:
            categories.append(post.category)
    category = ''
    if request.method == 'GET':
        if 'category' in request.GET:
            category = request.GET['category']
            if category != 'All':
                posts = posts.filter(category__name=category)
    ctx = {'posts' : posts.order_by('-post_date'), 'category' : category, 'categories' : categories, 
        'view' : 'MyArticlesView'}
    return render(request, 'blogapp/mainview.html', ctx)

def NoAccess(request):
    return render(request, 'blogapp/noaccess.html')

@login_required()
@user_passes_test(lambda u:u.is_superuser, login_url='blog:NoAccess')
def ApprovePost(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        post.visible = True
        post.locked = True
        post.save()
        messages.info(request, 'Post is approved and visible in Ozan.pl blog page.')
        return redirect('blog:MainView')
    return render(request, 'blogapp/postapprove.html', {'post' : post})



def LogoutView(request):
    messages.info(request, 'Successfully logged out...')
    logout(request)
    return redirect('blog:MainView')

templates/blogapp/mainview.html
{% extends "base.html" %}
{% block title %} BEAPRO BLOG {% endblock %}
{% block header %} BEAPRO BLOG {% endblock %}

{% block content %}

	{% for message in messages %}
		<div class="alert alert-secondary" role="alert">
			{{ message }}
		</div>
	{% endfor %}

    <div class="row">
		
        <div class="col">
            <div class="d-inline-block">
				<form method="GET">
					<div class="form-row align-items-center">
						<div class="col-auto my-1">
							<select class="custom-select mr-sm-2" name="category">
								<option value='All'>All Categories</option>

								{% for cat in categories %}
									<option value="{{ cat.name }}" {% if category == cat.name %} selected {% endif %} >{{cat.name}}</option>
								{% endfor %}
								
							</select>
						</div>
						<div class="col-auto my-1">
							<button type="submit" class="btn btn-secondary">Filter</button>
						</div>
					</div>
				</form>
			</div>
			<div class="float-right my-1">
				<div class="btn-group">
					<button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Actions
					</button>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="{% url 'blog:MainView' %}">All Articles</a>
						<a class="dropdown-item" href="{% url 'blog:MyArticlesView' %}">My Articles</a>
						<a class="dropdown-item" href="{% url 'blog:PostCreateView' %}">Create Post</a>
					</div>
				</div>
			</div>
		</div>
	
	</div>
		<div style="height: 0.5em; width: auto;"></div>
	<div class="row">
		<div style="margin: 1em; width: 100%;">
			<div class="card">
				<div class="card-body">
						<div class="col-md-12">
						
							{% for post in posts %}

								<h4><a href="{% url 'blog:PostDetailView' post.pk %}">{{ post.title }}</a></h4>
								
								<p class="text-justify">{{ post.snippet }}</p>
								
								<div>
									<span class="badge badge-secondary">
										Posted on {{ post.post_date|date:'d F Y'}} at {{ post.post_date|date:'H:i' }}
									</span>
									<div class="float-right">
										{% if view == 'MyArticlesView' %}
											{% if post.visible == True %}
												<span class="badge badge-success">Published</span> 
											{% else %}
												<span class="badge badge-danger">Not Published</span> 
											{% endif %}
										{% endif %}
										<span class="badge badge-secondary">{{ post.category }}</span> 
									</div>         
								</div>
								
								<hr>
							
							{% endfor %}
						</div>
				</div>
			</div>
		</div>
	
	</div>

{% endblock %}

templates/blogapp/noaccess.html
{% extends "base.html" %}
{% block title %} No Access {% endblock %}
{% block header %} No Access {% endblock %}

{% block content %}
     <br>
     <div class="jumbotron jumbotron-fluid">
          <div class="container">
          <h2 class="display-4 text-center">You don't have an access!</h2>
          <p class="text-center">
               Sorry, you don't have an access to this page.
               Please go back to the previous page to continue browsing 

               {% if not user.is_authenticated %}
                    or login if you have an account registered.
               {% else %}
                    . If you think you should have an access, please reach out to me using 
                    Contact page.
               {% endif %}
          </p>
          <br>
          <div class="text-center">
               <a class="btn btn-primary" href="javascript:history.back()">Go Back</a>
          </div>
          </div>
     </div>

{% endblock %}

templates/blogapp/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Post Create/Edit {% endblock %}
{% block header %} Post Create/Edit {% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <br>
        <input class="btn btn-primary" type="submit" value="Submit">
        <a class="btn btn-primary" href="{% url 'blog:MainView' %}">Cancel</a>
    </form>

    <script src="{% static '/js/js/post.js' %}"></script>

    <script>
        document.getElementById('id_snippet').style.height = "5em";
    </script>
{% endblock %}

templates/blogapp/postapprove.html
{% extends "base.html" %}
{% block title %} Approve Post {% endblock %}
{% block header %} Approve Post {% endblock %}

{% block content %}

<br>

<div class="jumbotron jumbotron-fluid">
    {% if not post.visible %}
        <div class="container">
            <h3 class="display-4 text-center font-3em-oz">Are you sure you want to approve "{{ post.title }}"?</h2>
            <br>
            <div class="text-center">
                <form method="post">
                    {% csrf_token %}
                    <input class="btn btn-primary black-button-oz" type="submit" value="Yes, approve.">
                    <a class="btn btn-primary black-button-oz" href="javascript:history.back()">No, Go Back</a>
                </form>
            </div> 
        </div>
    {% else %}
        <div class="container">
            <h3 class="display-4 text-center font-3em-oz">Post is already visible in the blog. There is no need to approve.</h2> <br>
            <div class="text-center">
                <a class="btn btn-primary black-button-oz" href="javascript:history.back()">No, Go Back</a>
            </div>
        </div>
    {% endif %}
</div>

{% endblock %}

templates/blogapp/postview.html
{% extends "base.html" %}
{% block title %} {{ post.title }} {% endblock %}
{% block header %} Post {% endblock %}

{% block head_other %}

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

{% endblock %}

{% block content %}

    <div class="container">
        <div class="row" style="margin-right: 1%; margin-left: 1%;">
            <div class="col">
                <!-- Title -->
                <h1 class="mt-4">{{post.title}}</h1>

                <!-- Author -->
                <p class="lead">
                    by {{ post.author.first_name }} {{ post.author.last_name }}
                </p>
        
                <hr>
        
                <!-- Date/Time -->
                <p>Posted on {{ post.post_date|date:'d F Y'}} at {{ post.post_date|date:'H:i' }}</p>
        
                <hr>

                <p>
                    {{ post.body|safe }}
                </p>
                <br/>
    
                <!-- Go Back -->
                <div class="text-center">
                    <a class="btn btn-primary mb-2" href="{% url 'blog:MainView' %}"> Go back </a>
                    {% if post.author == request.user and not post.locked or request.user.is_superuser %}
                        <a class="btn btn-primary mb-2" href="{% url 'blog:PostEditView' post.pk %}"> Edit Post</a>
                    {% endif %}
                </div>

                <!-- Likes -->
                {% if user.is_authenticated %}
                <form action="{% url 'blog:LikePost' post.pk %}?next={% url 'blog:PostDetailView' post.pk %}#likebutton" method="POST">
                    {% csrf_token %}
                    <button type="submit" name="post.id" value={{post.id}} class="btn btn-primary mb-2" id="likebutton">Like  <i class="fas fa-thumbs-up"></i></button>
                    {% if post.likes != 0 %}
                        <b>  {{ post.likes }} like{{post.likes|pluralize}}</b>
                    {% endif %}
                </form>
                {% endif %}
                <br>

                <!-- Information: Your comment/like submitted -->
                {% for message in messages %}
                    <div class="alert alert-secondary" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}

                <!-- Comments Form -->
                <div class="card my-4">
                    <h5 class="card-header text-center">Leave a Comment</h5>
                    <div class="card-body">
                        <form method="POST" action="{% url 'blog:PostDetailView' post.pk %}#likebutton">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control" name="name" placeholder="Your Name">
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" rows="3" name="comment" placeholder="Comment"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>

                <!-- Old Comments -->
                {% if comments %}
                    <h3 class="text-center">Comments</h3> <br/>
                    {% for comment in comments %}
                    <div class="alert alert-secondary" role="alert">
                        <div class="media mb-4">
                            <div class="media-body" style="margin-top: 0.8em;">
                                <h5 class="mt-0"><b>{{ comment.author }}</b></h5>
                                <small>{{ comment.comment_date }}</small> <br/>
                                <div style="height: 0.6em; width: auto;"></div>
                                {{ comment.body }}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}

            </div>
        </div>
    </div>

{% endblock %}