beapro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('student/',include('student.urls')),
    path('tutor/',include('tutor.urls')),
    path('blog/', include('blogapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "BEAPRO Admin"
admin.site.site_title = "Admin Portal"
admin.site.index_title = "Welcome to BEAPRO Admin Account"

blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.MainView, name='MainView'),
    path('post/<int:pk>', views.PostDetailView, name='PostDetailView'),
    path('post/create', views.PostCreateView.as_view(), name='PostCreateView'),
    path('post/<int:pk>/edit', views.PostEditView.as_view(), name='PostEditView'),
    path('post/<int:pk>/approve', views.ApprovePost, name='ApprovePost'),
    path('myposts/', views.MyArticlesView, name='MyArticlesView'),
    path('likepost/<int:pk>', views.LikePost, name='LikePost'),
    path('noaccess/', views.NoAccess, name='NoAccess'),
    # path('login/', views.LoginView, name='LoginView'),
    path('logout/', views.LogoutView, name='LogoutView'),
] 

tutor/urls.py
from django.urls import path
from .views import account_signup,account_login,logout_tutor,tutor_profile,connection_requests,decline_connection_request,connection_list_view,remove_connection_student


urlpatterns = [
    path('account/',account_login,name="tutor_account_login"),
    path('account/signup',account_signup,name="tutor_account_signup"),
    path('logout',logout_tutor, name="logout_tutor"),

    path('list/<user_id>', connection_list_view, name='student-list'),
    path('profile/',tutor_profile, name="tutor_profile"),
    path('connection_requests/<user_id>/',connection_requests,name='connection-requests'),
    path('remove_connection_student/',remove_connection_student,name='remove-connection-student'),
    path('decline_connection_request/<connection_request_id>/', decline_connection_request, name='decline-connection-request'),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel=icon href={% static 'img/beaprologo.png' %} sizes="16x16" type="image/png">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block head_other %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>
  </head>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'blog:MainView' %}">BEAPRO BLOG</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'blog:MainView' %}">Blog<span class="sr-only">(current)</span></a>
            <a class="nav-link active" href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a>
            {% if user.is_superuser %}
            <a class="nav-link active" href="{% url 'admin:index' %}">Admin Page <span class="sr-only">(current)</span></a>
            {% endif %}
            <!-- <a class="nav-link active" href="{% url 'blog:NoAccess' %}">No Access Page <span class="sr-only">(current)</span></a> -->
          </div>
          <div style="width: 25%; height: auto;"></div>
          <ul class="nav navbar-nav navbar-right">
            {% if not request.user.is_authenticated %}
              <li><a class="nav-link active" href="{% url 'index' %}">Login <span class="sr-only">(current)</span></a></li>
            {% else %}
              <li><a class="nav-link active" href="#">Welcome, <b>{{ request.user }}</b><span class="sr-only">(current)</span></a></li>
              <li><a class="nav-link active" href="{% url 'blog:LogoutView' %}">Logout <span class="sr-only">(current)</span></a></li>
            {% endif %}
          </ul>
        </div>
    </nav>

    <div style="margin-left: 4%; margin-right: 4%; margin-top: 1%;">
      <h1 class="text-center">{% block header %} {% endblock %}</h1>

      {% block content %}
      
      
      <script>
 if ('serviceWorker' in navigator) {
    console.log("Will the service worker register?");
    navigator.serviceWorker.register("{% url 'service-worker.js' %}") //note that I am using the url template here
      .then(function(reg){
        console.log("Yes, it did.");
     }).catch(function(err) {
       console.log("No it didn't. This happened:", err)
        console.log("err.message:", err.message)
    });
 }
</script>
      {% endblock %}
    </div>

    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://kit.fontawesome.com/e655379602.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  </body>
</html>

templates/google0648ddbac837895a.html
google-site-verification: google0648ddbac837895a.html

templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    <strong> {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        Important:
        {% else %}
        {{message.tags}}
        {% endif %}
        {{ message }}</strong> 
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endfor %}

{% endif %}